// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A structured application error that can be serialized and surfaced to the UI.
 */
export type AppError = { 
/**
 * Machine readable error code.
 */
code: string, 
/**
 * Human friendly message that can be shown directly to the user.
 */
message: string, 
/**
 * Arbitrary key/value pairs that provide additional context.
 */
context: Record<string, string> | undefined, 
/**
 * Optional nested cause that preserves the error chain.
 */
cause?: AppError, };
