// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AttachmentConflict = { relativePath: string, bundleUpdatedAt: number | null, liveUpdatedAt: number | null, reason: string, };
