// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentConflict } from "./AttachmentConflict";

export type AttachmentsPlan = { adds: number, updates: number, skips: number, conflicts: Array<AttachmentConflict>, };
