// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BackupManifest = { appVersion: string, schemaHash: string, dbSizeBytes: number, createdAt: string, sha256: string, };
