// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupEntry } from "./BackupEntry";

export type BackupOverview = { availableBytes: number, dbSizeBytes: number, requiredFreeBytes: number, retentionMaxCount: number, retentionMaxBytes: number, backups: Array<BackupEntry>, };
