// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupEntry } from "./BackupEntry";

export type BackupOverview = { available_bytes: number, db_size_bytes: number, required_free_bytes: number, retention_max_count: number, retention_max_bytes: number, backups: Array<BackupEntry>, };
