// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupManifest } from "./BackupManifest";

export type BackupEntry = { directory: string, sqlite_path: string, manifest_path: string, manifest: BackupManifest, total_size_bytes: number, };
