// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupManifest } from "./BackupManifest";

export type BackupEntry = { directory: string, sqlitePath: string, manifestPath: string, manifest: BackupManifest, totalSizeBytes: number, };
