// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BackupManifest = { app_version: string, schema_hash: string, db_size_bytes: number, created_at: string, sha256: string, };
