// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Category = { id: string, household_id: string, name: string, slug: string, color: string, position: number, z: number, is_visible: boolean, created_at: number, updated_at: number, deleted_at?: number, };
