// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import type { Note } from "./Note";
import type { NoteLink } from "./NoteLink";

export type ContextNotesPage = { notes: Note[], links: NoteLink[], next_cursor?: string };
