// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DbHealthCheck = { name: string, passed: boolean, duration_ms: number, details?: string, };
