// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DbHealthCheck } from "../../src-tauri/bindings/DbHealthCheck";
import type { DbHealthOffender } from "../../src-tauri/bindings/DbHealthOffender";
import type { DbHealthStatus } from "../../src-tauri/bindings/DbHealthStatus";

export type DbHealthReport = { status: DbHealthStatus, checks: Array<DbHealthCheck>, offenders: Array<DbHealthOffender>, schema_hash: string, app_version: string, generated_at: string, };
