// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DbHealthStatus = "ok" | "error";

export type DbHealthCheck = { name: string, passed: boolean, duration_ms: number, details?: string, };

export type DbHealthOffender = { table: string, rowid: number, message: string, };

export type DbHealthReport = { status: DbHealthStatus, checks: Array<DbHealthCheck>, offenders?: Array<DbHealthOffender>, schema_hash: string, app_version: string, generated_at: string, };
