// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DbHealthCheck } from "./DbHealthCheck";
import type { DbHealthOffender } from "./DbHealthOffender";
import type { DbHealthStatus } from "./DbHealthStatus";

export type DbHealthReport = { status: DbHealthStatus, checks: Array<DbHealthCheck>, offenders: Array<DbHealthOffender>, schema_hash: string, app_version: string, generated_at: string, };
