// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";
import type { DbHealthReport } from "./DbHealthReport";
import type { DbRepairStepReport } from "./DbRepairStepReport";

export type DbRepairSummary = {
  success: boolean,
  steps: Array<DbRepairStepReport>,
  error?: AppError | null,
  health_report?: DbHealthReport | null,
  backup_directory?: string | null,
  backup_sqlite_path?: string | null,
  archived_db_path?: string | null,
  duration_ms: number,
};
