// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DbRepairStep } from "./DbRepairStep";
import type { DbRepairStepState } from "./DbRepairStepState";

export type DbRepairStepReport = {
  step: DbRepairStep,
  status: DbRepairStepState,
  message?: string | null,
};
