// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";
import type { DbHealthReport } from "./DbHealthReport";
import type { DbRepairStepReport } from "./DbRepairStepReport";

export type DbRepairSummary = { success: boolean, steps: Array<DbRepairStepReport>, error?: AppError, health_report?: DbHealthReport, backup_directory?: string, backup_sqlite_path?: string, archived_db_path?: string, duration_ms: number, };
