// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Event = { id: string, household_id: string, title: string, starts_at: number, reminder?: number, created_at: number, updated_at: number, deleted_at?: number, };
