// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportMode } from "./ImportMode";
import type { TableExecutionSummary } from "./TableExecutionSummary";
import type { AttachmentExecutionSummary } from "./AttachmentExecutionSummary";

export type ExecutionReport = { mode: ImportMode, tables: Record<string, TableExecutionSummary>, attachments: AttachmentExecutionSummary, };
