// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentExecutionSummary } from "./AttachmentExecutionSummary";
import type { ImportMode } from "./ImportMode";
import type { TableExecutionSummary } from "./TableExecutionSummary";

export type ExecutionReport = { mode: ImportMode, tables: { [key in string]?: TableExecutionSummary }, attachments: AttachmentExecutionSummary, };
