// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentsInfo } from "./AttachmentsInfo";
import type { TableInfo } from "./TableInfo";

export type ExportManifest = { appVersion: string, schemaVersion: string, createdAt: string, tables: { [key in string]?: TableInfo }, attachments: AttachmentsInfo, };
