// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExportEntryDto = { directory: string, manifestPath: string, verifyShPath: string, verifyPs1Path: string, };
