// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HardRepairTableStats } from "./HardRepairTableStats";
import type { HardRepairSkippedRow } from "./HardRepairSkippedRow";

export type HardRepairRecoveryReport = { appVersion: string, tables: Record<string, HardRepairTableStats>, skippedExamples: Array<HardRepairSkippedRow>, completedAt: string, integrityOk: boolean, integrityError?: string, foreignKeyErrors?: Array<HardRepairSkippedRow>, };
