// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HardRepairRecoveryReport } from "./HardRepairRecoveryReport";

export type HardRepairOutcome = { success: boolean, omitted: boolean, reportPath: string, preBackupDirectory: string, archivedDbPath?: string, rebuiltDbPath?: string, recovery: HardRepairRecoveryReport, };
