// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportMode } from "./ImportMode";
import type { TablePlan } from "./TablePlan";
import type { AttachmentsPlan } from "./AttachmentsPlan";

export type ImportPlan = { mode: ImportMode, tables: Record<string, TablePlan>, attachments: AttachmentsPlan, };
