// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutionReport } from "./ExecutionReport";
import type { ImportMode } from "./ImportMode";
import type { ImportPlan } from "./ImportPlan";
import type { ValidationReport } from "./ValidationReport";

export type ImportExecuteDto = { bundlePath: string, mode: ImportMode, validation: ValidationReport, plan: ImportPlan, planDigest: string, execution: ExecutionReport, reportPath: string, };
