// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportMode } from "./ImportMode";
import type { ValidationReport } from "./ValidationReport";
import type { ImportPlan } from "./ImportPlan";

export type ImportPreviewDto = { bundlePath: string, mode: ImportMode, validation: ValidationReport, plan: ImportPlan, planDigest: string, };
