// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentsPlan } from "./AttachmentsPlan";
import type { ImportMode } from "./ImportMode";
import type { TablePlan } from "./TablePlan";

export type ImportPlan = { mode: ImportMode, tables: { [key in string]?: TablePlan }, attachments: AttachmentsPlan, };
