// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Note = { id: string, household_id: string, category_id?: string, position: number, created_at: number, updated_at: number, deleted_at?: number, text: string, color: string, x: number, y: number, z?: number, deadline?: number, deadline_tz?: string };
