// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Note } from "./Note";

export type NotesDeadlineRangePage = { items: Array<Note>, cursor?: string, };
