// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import type { NoteLinkEntityType } from "./NoteLinkEntityType";

export type NoteLink = { id: string, household_id: string, note_id: string, entity_type: NoteLinkEntityType, entity_id: string, relation: string, created_at: number, updated_at: number };
