// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SearchResult = { "kind": "File", id: string, filename: string, updated_at: number, } | { "kind": "Event", id: string, title: string, start_at_utc: number, tz: string, } | { "kind": "Note", id: string, snippet: string, updated_at: number, color: string, } | { "kind": "Vehicle", id: string, make: string, model: string, reg: string, updated_at: number, nickname: string, } | { "kind": "Pet", id: string, name: string, species: string, updated_at: number, };
