// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Vehicle = { id: string, household_id: string, name: string, make?: string, model?: string, reg?: string, vin?: string, next_mot_due?: number, next_service_due?: number, created_at: number, updated_at: number, deleted_at?: number, position: number, };
