name: Model check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  models:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: dtolnay/rust-toolchain@stable
      - run: npm ci
      - run: npm run generate:models
      - run: git diff --exit-code
